### PR TITLE
Updated eslint to 6.2.1 and eslint-config-stripes to 5

### PR DESCRIPTION
**Pull request by ryandberger**

### CODE REVIEW

**Comment by MikeTaylor** [comment]
But you should all be using `categorical-logger` by now!

**Comment by ryandberger** [comment]
> But you should all be using `categorical-logger` by now!

Oh? Should this repo be marked as DEPRECATED?

**Comment by MikeTaylor** [comment]
I guess it should, really. Is there a formal way to do that, or do I just shove "THIS IS DEPRECATED" into the README?

**Comment by MikeTaylor** [comment]
Oh, wait — I did that nearly a year ago! https://github.com/folio-org/stripes-logger/commit/0d1b4c5f94e685038f68e92afbfe1d1d36cf7505

**Comment by ryandberger** [comment]
> Oh, wait — I did that nearly a year ago! [0d1b4c5](https://github.com/folio-org/stripes-logger/commit/0d1b4c5f94e685038f68e92afbfe1d1d36cf7505)

In addition, the repo description should start with `*DEPRECATED*` and then be marked as archived under the repo settings. See https://github.com/folio-org/stripes-loader for an example.

**Comment by MikeTaylor** [comment]
Oh, useful! Thank you!

Turns out, though, I don't have permission to make that edit. Do you?

**Comment by ryandberger** [comment]
> Oh, useful! Thank you!
> 
> Turns out, though, I don't have permission to make that edit. Do you?

I don't, I'll try to find out who does and ping them to update.

**Comment by MikeTaylor** [comment]
Appreciated!

**Pull request merged**
